model:
  name: sdlpp
  params:
    T: 100
    target_d: 13
    k: 8
    miu: 0.1
    thr: 0.95

disambig:
  name: knn_propagation
  params:
    use_sample_reliability: false
    use_class_balance: false

classifier:
  name: knn
  params:
    n_neighbors: 5

method_tag: sdlpp_baseline
